[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aurelia"
version = "0.1.0"
description = "Advanced Scientific Machine Learning Framework"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["aurelia"]