# config/train_config.yaml

# Path settings
data_path: "data/dataset.csv"
model_output_dir: "models"
model_filename: "random_forest_model.pkl"

# Model settings
model_type: "RandomForestRegressor"
n_estimators: 100
max_depth: null
random_state: 42
n_jobs: -1

# Training settings
test_size: 0.2
